# Copyright (c) KMG. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
##

"""Dependency-free operational defaults shared across application boundaries."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BoundedIntegerSetting:
    """One environment-controlled integer and its accepted range."""

    environment: str
    default: int
    minimum: int
    maximum: int


DEFAULT_DASHBOARD_PORT = 9721
DEFAULT_PROMETHEUS_PORT = 9090
DEFAULT_GRAFANA_PORT = 3000
DEFAULT_RETENTION_DAYS = 7
DEFAULT_SCRAPE_INTERVAL_SECONDS = 5
DEFAULT_STATUS_INTERVAL_SECONDS = 60
MAX_STATUS_INTERVAL_SECONDS = 86_400
DEFAULT_MANAGEMENT_BIND = "0.0.0.0"
DEFAULT_PROMETHEUS_BIND = "127.0.0.1"
DEFAULT_GRAFANA_BIND = "0.0.0.0"
DEFAULT_TARGET_HOST = "127.0.0.1"
DEFAULT_LOG_LEVEL = "INFO"
SUPPORTED_LOG_LEVELS = frozenset({"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"})
DEFAULT_HOME_DIRECTORY_NAME = ".sbk-dashboard"
PORTABLE_HOME_ENVIRONMENT = "SBK_DASHBOARD_HOME"
DATA_DIRECTORY_ENVIRONMENT = "SBK_DASHBOARD_DATA_DIR"
LAUNCHER_DIRECTORY_ENVIRONMENT = "SBK_DASHBOARD_LAUNCHER_DIR"
MANAGEMENT_BIND_ENVIRONMENT = "SBK_DASHBOARD_BIND"
LOG_LEVEL_ENVIRONMENT = "SBK_DASHBOARD_LOG_LEVEL"
RETENTION_DAYS_ENVIRONMENT = "SBK_DASHBOARD_DISK_RETENTION_DAYS"
SCRAPE_INTERVAL_ENVIRONMENT = "SBK_DASHBOARD_SCRAPE_SECONDS"
STATUS_INTERVAL_ENVIRONMENT = "SBK_DASHBOARD_STATUS_SECONDS"
DEFAULT_TARGET_HOST_ENVIRONMENT = "SBK_DASHBOARD_DEFAULT_TARGET_HOST"
PROMETHEUS_BINARY_ENVIRONMENT = "SBK_DASHBOARD_PROMETHEUS_BIN"
PROMETHEUS_PORT_ENVIRONMENT = "SBK_DASHBOARD_PROMETHEUS_PORT"
PROMETHEUS_BIND_ENVIRONMENT = "SBK_DASHBOARD_PROMETHEUS_BIND"
GRAFANA_HOME_ENVIRONMENT = "SBK_DASHBOARD_GRAFANA_HOME"
GRAFANA_PORT_ENVIRONMENT = "SBK_DASHBOARD_GRAFANA_PORT"
GRAFANA_BIND_ENVIRONMENT = "SBK_DASHBOARD_GRAFANA_BIND"
GRAFANA_URL_ENVIRONMENT = "SBK_DASHBOARD_GRAFANA_URL"
MONITORING_PROPERTIES_ENVIRONMENT = "SBK_DASHBOARD_MONITORING_PROPERTIES"
BOOTSTRAP_RUNTIME_KIND_ENVIRONMENT = "SBK_DASHBOARD_BOOTSTRAP_RUNTIME_KIND"
BOOTSTRAP_RUNTIME_STATE_ENVIRONMENT = "SBK_DASHBOARD_BOOTSTRAP_RUNTIME_STATE"
BOOTSTRAP_RUNTIME_PATH_ENVIRONMENT = "SBK_DASHBOARD_BOOTSTRAP_RUNTIME_PATH"
BOOTSTRAP_DIAGNOSTICS_REPORTED_ENVIRONMENT = "SBK_DASHBOARD_BOOTSTRAP_DIAGNOSTICS_REPORTED"

HTTP_WORKERS = BoundedIntegerSetting("SBK_DASHBOARD_HTTP_WORKERS", 8, 1, 128)
HTTP_QUEUE_CAPACITY = BoundedIntegerSetting("SBK_DASHBOARD_HTTP_QUEUE", 64, 0, 10_000)
REQUEST_TIMEOUT_SECONDS = BoundedIntegerSetting("SBK_DASHBOARD_REQUEST_TIMEOUT_SECONDS", 15, 1, 300)
HEALTH_RESPONSE_MEBIBYTES = BoundedIntegerSetting("SBK_DASHBOARD_HEALTH_RESPONSE_MB", 4, 1, 64)
SUPERVISOR_INTERVAL_SECONDS = BoundedIntegerSetting("SBK_DASHBOARD_SUPERVISOR_SECONDS", 5, 1, 60)
PROCESS_LOG_MEBIBYTES = BoundedIntegerSetting("SBK_DASHBOARD_PROCESS_LOG_MB", 10, 1, 1024)
PROCESS_LOG_BACKUPS = BoundedIntegerSetting("SBK_DASHBOARD_PROCESS_LOG_BACKUPS", 3, 0, 100)
MAX_TARGETS = BoundedIntegerSetting("SBK_DASHBOARD_MAX_TARGETS", 10_000, 1, 1_000_000)
COMPARISON_TARGETS = BoundedIntegerSetting(
    "SBK_DASHBOARD_MAX_COMPARISON_TARGETS", 4, 2, 32
)
TARGET_HEALTH_TIMEOUT_SECONDS = BoundedIntegerSetting(
    "SBK_DASHBOARD_TARGET_HEALTH_TIMEOUT_SECONDS", 4, 1, 300
)
PROMETHEUS_STARTUP_TIMEOUT_SECONDS = BoundedIntegerSetting(
    "SBK_DASHBOARD_PROMETHEUS_STARTUP_TIMEOUT_SECONDS", 45, 1, 900
)
GRAFANA_STARTUP_TIMEOUT_SECONDS = BoundedIntegerSetting(
    "SBK_DASHBOARD_GRAFANA_STARTUP_TIMEOUT_SECONDS", 120, 1, 900
)
GRAFANA_DASHBOARD_PROBE_TIMEOUT_SECONDS = 1
DASHBOARD_READINESS_RETRY_DELAYS_SECONDS = (0.5, 1, 2, 4, 5, 5, 5, 5, 5, 5)

BYTES_PER_KIBIBYTE = 1024
BYTES_PER_MEBIBYTE = BYTES_PER_KIBIBYTE * BYTES_PER_KIBIBYTE
BYTES_PER_GIBIBYTE = BYTES_PER_KIBIBYTE * BYTES_PER_MEBIBYTE
MAX_DOWNLOAD_BYTES = 2 * BYTES_PER_GIBIBYTE
PROCESS_CREATE_TIME_TOLERANCE_SECONDS = 0.01

# Browser behavior is derived from these server-owned values when app.js is served.
MAX_REQUEST_BYTES = 64 * BYTES_PER_KIBIBYTE
MAX_TRACKED_CLIENTS = 10_000
LANDING_ACTIVITY_SECONDS = 120
GRAFANA_ACTIVITY_SECONDS = 300
TARGET_REFRESH_MILLISECONDS = 10_000
LANDING_HEARTBEAT_MILLISECONDS = 30_000
CLIENT_ID_RANDOM_BYTES = 16
MIN_CLIENT_ID_CHARACTERS = 16
MAX_CLIENT_ID_CHARACTERS = 64
