"""Dependency-free operational defaults shared across application boundaries."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BoundedIntegerSetting:
    """One environment-controlled integer and its accepted range."""

    environment: str
    default: int
    minimum: int
    maximum: int


DEFAULT_DASHBOARD_PORT = 9721
DEFAULT_PROMETHEUS_PORT = 9090
DEFAULT_GRAFANA_PORT = 3000
DEFAULT_RETENTION_DAYS = 7
DEFAULT_SCRAPE_INTERVAL_SECONDS = 5
DEFAULT_STATUS_INTERVAL_SECONDS = 60
MAX_STATUS_INTERVAL_SECONDS = 86_400
DEFAULT_MANAGEMENT_BIND = "0.0.0.0"
DEFAULT_PROMETHEUS_BIND = "127.0.0.1"
DEFAULT_GRAFANA_BIND = "0.0.0.0"
DEFAULT_TARGET_HOST = "127.0.0.1"
DEFAULT_LOG_LEVEL = "INFO"
SUPPORTED_LOG_LEVELS = frozenset({"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"})
DEFAULT_HOME_DIRECTORY_NAME = ".sbk-dashboard"
PORTABLE_HOME_ENVIRONMENT = "SBK_DASHBOARD_HOME"
DATA_DIRECTORY_ENVIRONMENT = "SBK_DASHBOARD_DATA_DIR"
LAUNCHER_DIRECTORY_ENVIRONMENT = "SBK_DASHBOARD_LAUNCHER_DIR"
BOOTSTRAP_RUNTIME_KIND_ENVIRONMENT = "SBK_DASHBOARD_BOOTSTRAP_RUNTIME_KIND"
BOOTSTRAP_RUNTIME_STATE_ENVIRONMENT = "SBK_DASHBOARD_BOOTSTRAP_RUNTIME_STATE"
BOOTSTRAP_RUNTIME_PATH_ENVIRONMENT = "SBK_DASHBOARD_BOOTSTRAP_RUNTIME_PATH"
BOOTSTRAP_DIAGNOSTICS_REPORTED_ENVIRONMENT = "SBK_DASHBOARD_BOOTSTRAP_DIAGNOSTICS_REPORTED"

HTTP_WORKERS = BoundedIntegerSetting("SBK_DASHBOARD_HTTP_WORKERS", 8, 1, 128)
HTTP_QUEUE_CAPACITY = BoundedIntegerSetting("SBK_DASHBOARD_HTTP_QUEUE", 64, 0, 10_000)
REQUEST_TIMEOUT_SECONDS = BoundedIntegerSetting("SBK_DASHBOARD_REQUEST_TIMEOUT_SECONDS", 15, 1, 300)
HEALTH_RESPONSE_MEBIBYTES = BoundedIntegerSetting("SBK_DASHBOARD_HEALTH_RESPONSE_MB", 4, 1, 64)
SUPERVISOR_INTERVAL_SECONDS = BoundedIntegerSetting("SBK_DASHBOARD_SUPERVISOR_SECONDS", 5, 1, 60)
PROCESS_LOG_MEBIBYTES = BoundedIntegerSetting("SBK_DASHBOARD_PROCESS_LOG_MB", 10, 1, 1024)
PROCESS_LOG_BACKUPS = BoundedIntegerSetting("SBK_DASHBOARD_PROCESS_LOG_BACKUPS", 3, 0, 100)
MAX_TARGETS = BoundedIntegerSetting("SBK_DASHBOARD_MAX_TARGETS", 10_000, 1, 1_000_000)
TARGET_HEALTH_TIMEOUT_SECONDS = BoundedIntegerSetting(
    "SBK_DASHBOARD_TARGET_HEALTH_TIMEOUT_SECONDS", 4, 1, 300
)
PROMETHEUS_STARTUP_TIMEOUT_SECONDS = BoundedIntegerSetting(
    "SBK_DASHBOARD_PROMETHEUS_STARTUP_TIMEOUT_SECONDS", 45, 1, 900
)
GRAFANA_STARTUP_TIMEOUT_SECONDS = BoundedIntegerSetting(
    "SBK_DASHBOARD_GRAFANA_STARTUP_TIMEOUT_SECONDS", 120, 1, 900
)

MAX_DOWNLOAD_BYTES = 2 * 1024 * 1024 * 1024
PROCESS_CREATE_TIME_TOLERANCE_SECONDS = 0.01

# Browser behavior is derived from these server-owned values when app.js is served.
MAX_REQUEST_BYTES = 64 * 1024
MAX_TRACKED_CLIENTS = 10_000
LANDING_ACTIVITY_SECONDS = 120
GRAFANA_ACTIVITY_SECONDS = 300
TARGET_REFRESH_MILLISECONDS = 10_000
LANDING_HEARTBEAT_MILLISECONDS = 30_000
CLIENT_ID_RANDOM_BYTES = 16
MIN_CLIENT_ID_CHARACTERS = 16
MAX_CLIENT_ID_CHARACTERS = 64
