# Copyright (c) KMG. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
##

services:
  sbk-dashboard:
    image: sbk-dashboard:1.26.8.3
    pull_policy: never
    build:
      context: .
      args:
        VCS_REF: ${SBK_DASHBOARD_VCS_REF:-local}
        BUILD_DATE: ${SBK_DASHBOARD_BUILD_DATE:-1970-01-01T00:00:00Z}
