# Copyright (c) KMG. All Rights Reserved.
# Licensed under the Apache License, Version 2.0.

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8 --enable-native-access=ALL-UNNAMED

dashboardVersion=1.0.0
javaVersion=25
checkstyleToolVersion=13.9.0
commonsCliVersion=1.11.0
jacksonVersion=2.21.1
junitVersion=6.1.2
