#!/bin/sh
# Copyright (c) KMG. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
##

set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
COMMAND=${1:-foreground}
case "$COMMAND" in
    start|foreground)
        [ "$#" -eq 0 ] || shift
        exec "$ROOT/scripts/start-sbk-dashboard.sh" "$@"
        ;;
    background)
        shift
        exec "$ROOT/scripts/start-sbk-dashboard-background.sh" "$@"
        ;;
    stop)
        shift
        exec "$ROOT/scripts/stop-sbk-dashboard.sh" "$@"
        ;;
    repair)
        shift
        exec "$ROOT/scripts/sbk-dashboard-launch.sh" repair "$@"
        ;;
    *)
        exec "$ROOT/scripts/start-sbk-dashboard.sh" "$@"
        ;;
esac
